import http from '@/api/http'
import type { AttachmentResponse, UploadAttachmentBody } from '@/api/generated/model'

/**
 * `POST /tickets/{ticketId}/attachments`, by hand rather than through the
 * generated `uploadAttachment`.
 *
 * ⚠ **This exists because of a defect, not a preference.** Orval emits
 *
 *     headers: { 'Content-Type': 'multipart/form-data' }
 *
 * on the generated call (`api/generated/attachments/attachments.ts`), and
 * `api/http.ts` spreads caller headers *after* the branch that deliberately
 * omits a content type for a `FormData` body:
 *
 *     ...(isForm ? {} : …),
 *     ...headers,          // ← the generated header wins
 *
 * A multipart body is unparseable without the `boundary` parameter, and the
 * boundary is generated by the browser when — and only when — it is left to set
 * the header itself. Passing the bare type suppresses that. MSW's
 * `request.formData()` is forgiving enough to hide it under `npm run dev` and in
 * every test; a real Spring `@RequestPart` returns 400 or 500 for every upload.
 *
 * The fix belongs in one of two files, **neither of which is Stream C's**:
 * `api/http.ts` is Stream D's (D-003, stated in its own header) and one line
 * would do it — drop an incoming `Content-Type` when the body is `FormData`.
 * `api/generated/` is generated and must never be hand-edited. So this wrapper
 * sends the same request without the header and stays correct either way: when
 * Stream D lands the fix, this keeps working unchanged, and it can then be
 * deleted in favour of `useUploadAttachment`.
 *
 * Everything else is imported from the generated code — the body type, the
 * response type, the URL shape — so a contract change still reaches this.
 */
export function uploadTicketAttachment(
  ticketId: string,
  body: UploadAttachmentBody,
  signal?: AbortSignal,
): Promise<AttachmentResponse> {
  const form = new FormData()
  form.append('file', body.file)
  if (body.isClientVisible !== undefined) form.append('isClientVisible', String(body.isClientVisible))
  if (body.commentId !== undefined) form.append('commentId', String(body.commentId))

  return http<AttachmentResponse>({
    url: `/tickets/${ticketId}/attachments`,
    method: 'POST',
    data: form,
    signal,
  })
}
