#!/usr/bin/env bash
# EduTrack — 09:00 plan refresh.
#
# Pull, re-derive status from git, reschedule, publish, notify, push.
# Safe to run by hand at any time; running twice in a day just posts a second
# brief with the same content.
#
#   tools/plan/daily.sh              # the real thing
#   tools/plan/daily.sh --dry-run    # recompute and print, change nothing
set -euo pipefail

cd "$(dirname "$0")/../.."
DRY=""; [[ "${1:-}" == "--dry-run" ]] && DRY="--dry-run"
TODAY="$(date +%F)"
DOW="$(date +%u)"   # 1..7, Mon..Sun

if [[ "$DOW" -ge 6 ]]; then
  echo "$TODAY is a weekend — the plan only moves on working days."
  exit 0
fi

echo "── EduTrack plan refresh · $TODAY ─────────────────────────────────"

# 1 · latest integrated state. Fetch always; only fast-forward if we can, so a
#     dirty tree or local work is never clobbered by a scheduled job.
git fetch --all --prune --quiet
if git symbolic-ref -q HEAD >/dev/null && [[ -z "$(git status --porcelain)" ]]; then
  git merge --ff-only "@{u}" --quiet 2>/dev/null || echo "  (not fast-forwardable — continuing on local state)"
else
  echo "  (working tree dirty — continuing without pulling)"
fi

# 2 · reschedule
python3 tools/plan/extract_tasks.py
python3 tools/plan/schedule.py ${DRY}
[[ -n "$DRY" ]] && { python3 tools/plan/notify.py --dry-run --date "$TODAY"; exit 0; }

# 3 · commit the refreshed plan. Generated files only — never anything else.
git add docs/plan/GANTT.md docs/plan/gantt.html docs/plan/tasks.csv \
        "docs/plan/standup/$TODAY.md" 2>/dev/null || true
if ! git diff --cached --quiet; then
  git commit -q -m "chore(plan): daily schedule refresh $TODAY" \
    -m "Regenerated by tools/plan/daily.sh. Status derived from git." \
    -m "Co-Authored-By: Claude Opus 5 (1M context) <noreply@anthropic.com>"
  git push --quiet origin HEAD && echo "  pushed plan refresh"
else
  echo "  plan unchanged — nothing to commit"
fi

# 4 · notify. Set EDUTRACK_NOTIFY=0 to regenerate without messaging anyone.
if [[ "${EDUTRACK_NOTIFY:-1}" == "1" ]]; then
  python3 tools/plan/notify.py --date "$TODAY"
else
  echo "  notifications suppressed (EDUTRACK_NOTIFY=0)"
fi

echo "── done ───────────────────────────────────────────────────────────"
