package com.edunext.edutrack.api.feature.auth;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.security.SecureRandom;
import java.util.Base64;
import java.util.List;

/**
 * A-020 · credential verification. Blueprint §10.1.
 *
 * <p>Three properties this class exists to hold, each of which is easy to lose
 * in an innocuous-looking refactor:
 *
 * <ol>
 *   <li><b>Every outcome costs one Argon2id verification.</b> The obvious
 *       implementation returns early when the username is unknown, and by doing
 *       so answers "does this account exist?" in a few hundred microseconds
 *       versus the ~100 ms a real verification takes. That gap is measurable
 *       across the internet and turns a login form into a staff directory. The
 *       decoy hash below closes it.</li>
 *   <li><b>Every failure is the same failure.</b> Unknown user, wrong password
 *       and deactivated account all raise {@link InvalidCredentialsException},
 *       which has no room to carry a reason.</li>
 *   <li><b>The password never leaves this method.</b> Not into a log, not into
 *       the exception, not into the returned object.</li>
 * </ol>
 *
 * <p><b>Not in this task, deliberately.</b> A-021 owns {@code failed_attempts},
 * the 15-minute lockout and the admin alert; A-022 owns the access token; A-023
 * the refresh cookie; A-026 the forced-change redirect; A-029 the TOTP
 * challenge. §10.1 also opens with a per-IP rate limit, which is Redis-backed
 * and pairs naturally with A-021's counter — building half of it here would
 * mean two throttles to reason about. Until A-021 lands there is <b>no limit on
 * guess volume</b>; Argon2id's cost is the only brake.
 */
@Service
class AuthenticationService {

    private static final Logger log = LoggerFactory.getLogger(AuthenticationService.class);

    private final AuthUserRepository users;
    private final PasswordEncoder passwordEncoder;

    /**
     * A real Argon2id hash of a value nobody knows, verified against whenever
     * the username does not exist.
     *
     * <p>Computed once at startup rather than hardcoded, for two reasons: a
     * literal in the source would have to be regenerated by hand if §10.3's
     * parameters ever change, and a malformed literal would be rejected by
     * {@code matches()} in microseconds — reintroducing the very timing
     * difference it is here to remove, silently and only for unknown users.
     *
     * <p>The source password is random per process, so the decoy cannot be
     * matched even by someone holding this file.
     */
    private final String decoyHash;

    AuthenticationService(AuthUserRepository users, PasswordEncoder passwordEncoder) {
        this.users = users;
        this.passwordEncoder = passwordEncoder;
        this.decoyHash = passwordEncoder.encode(randomSecret());
    }

    /**
     * Verifies a username and password and resolves the caller's scope.
     *
     * <p>Read-only: A-020 writes nothing. {@code last_login_at} and the
     * {@code failed_attempts} reset belong with A-021's counter, and the
     * {@code LOGIN_SUCCESS} audit row with A-071 — putting a write here now
     * would mean a second, competing update path once those land.
     *
     * @throws InvalidCredentialsException on every failure, without saying which
     */
    @Transactional(readOnly = true)
    AuthenticatedUser authenticate(String username, String rawPassword) {
        AuthUserRow user = users.findByUsername(username).orElse(null);

        // Both branches run the full KDF. Do not "optimise" this into an early
        // return when `user` is null — that is the enumeration oracle.
        String hashToVerify = (user != null) ? user.passwordHash() : decoyHash;
        boolean passwordMatches = passwordEncoder.matches(rawPassword, hashToVerify);

        if (user == null || !passwordMatches || !user.active()) {
            // Logged at DEBUG and without the username: an INFO-level record of
            // every failed attempt writes a list of valid usernames — and
            // eventually a mistyped password — into a file with far wider read
            // access than the users table. A-071's audit log is the deliberate,
            // access-controlled place for this.
            log.debug("Login rejected");
            throw new InvalidCredentialsException();
        }

        return resolveScope(user);
    }

    /**
     * Loads the §10.1 claim set. Runs only after the password verified, so a
     * failed attempt costs one indexed lookup and one hash — never these three
     * queries.
     */
    private AuthenticatedUser resolveScope(AuthUserRow user) {
        List<String> permissions = users.findPermissionCodesByRoleId(user.roleId());
        List<Long> projectIds = users.findProjectIdsByUserId(user.id());
        List<Long> reporteeIds = users.findReporteeIdsByManagerId(user.id());

        return new AuthenticatedUser(
                user.id(),
                user.username(),
                user.email(),
                user.fullName(),
                user.roleCode(),
                user.timezone(),
                user.mustChangePassword(),
                permissions,
                projectIds,
                reporteeIds);
    }

    private static String randomSecret() {
        byte[] bytes = new byte[32];
        new SecureRandom().nextBytes(bytes);
        return Base64.getEncoder().encodeToString(bytes);
    }
}
