package com.edunext.edutrack.api.feature.auth;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.security.SecureRandom;
import java.time.Instant;
import java.util.Base64;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * A-020 · credential verification. Blueprint §10.1.
 *
 * <p>Three properties this class exists to hold, each of which is easy to lose
 * in an innocuous-looking refactor:
 *
 * <ol>
 *   <li><b>Every outcome costs one Argon2id verification.</b> The obvious
 *       implementation returns early when the username is unknown, and by doing
 *       so answers "does this account exist?" in a few hundred microseconds
 *       versus the ~100 ms a real verification takes. That gap is measurable
 *       across the internet and turns a login form into a staff directory. The
 *       decoy hash below closes it.</li>
 *   <li><b>Every failure is the same failure.</b> Unknown user, wrong password
 *       and deactivated account all raise {@link InvalidCredentialsException},
 *       which has no room to carry a reason.</li>
 *   <li><b>The password never leaves this method.</b> Not into a log, not into
 *       the exception, not into the returned object.</li>
 * </ol>
 *
 * <p><b>Not in this task, deliberately.</b> A-022 owns the access token; A-023
 * the refresh cookie; A-026 the forced-change redirect.
 *
 * <p><b>A-029 added the TOTP challenge</b>, and its placement is part of the
 * design above rather than an addition to it: {@link TotpService#verifyForLogin}
 * is called after the password verification and the lockout check, so a
 * "this account needs a code" answer is only ever given to somebody who has
 * already proved the password. Reaching it earlier would confirm both that an
 * account exists and that it is protected — a list of exactly whom to phish —
 * and would answer in a measurably different time from an account without 2FA.
 *
 * <p><b>Two gaps remained after A-021. Both are closed by A-076</b>
 * ({@link LoginRateLimiter}), which sits in front of this method rather than
 * inside it.
 *
 * <p>First, <b>nothing capped guess volume.</b> §10.1 opens with a "10 attempts
 * / 15 min / IP" limit. A-021's counter stops repeated guessing against
 * <i>one</i> account; it does nothing about one common password sprayed across a
 * thousand usernames, where no single account ever reaches five failures. A
 * purely per-IP limit was built and removed — it puts an entire office behind
 * one NAT address into a shared budget, so one colleague's typos lock out
 * everyone around them. A-076 is two-dimensional instead: attempts per
 * {@code (client, identifier)}, and separately the number of <i>distinct</i>
 * identifiers one source has <i>failed</i> against.
 *
 * <p>Second, and consequently, <b>a rejected attempt is expensive</b> — every
 * one costs a full Argon2id verification (~175 ms and 64 MB, measured), because
 * the lock is checked after the hash rather than before it. That ordering is
 * deliberate and must not be "optimised": checking the lock first would make a
 * locked account answer faster than an unlocked one, which leaks exactly what
 * the uniform timing above exists to hide. A-076 bounds the cost without
 * touching that ordering, by refusing before this method is entered at all —
 * which it may do only because its budget is keyed on what was submitted and
 * never resolves it, so its {@code 429} says nothing about the account.
 */
@Service
class AuthenticationService {

    private static final Logger log = LoggerFactory.getLogger(AuthenticationService.class);

    private final AuthUserRepository users;
    private final PasswordEncoder passwordEncoder;
    private final LoginAttemptRecorder attempts;
    private final PasswordPolicy passwordPolicy;
    private final TotpService twoFactor;

    /**
     * A real Argon2id hash of a value nobody knows, verified against whenever
     * the username does not exist.
     *
     * <p>Computed once at startup rather than hardcoded, for two reasons: a
     * literal in the source would have to be regenerated by hand if §10.3's
     * parameters ever change, and a malformed literal would be rejected by
     * {@code matches()} in microseconds — reintroducing the very timing
     * difference it is here to remove, silently and only for unknown users.
     *
     * <p>The source password is random per process, so the decoy cannot be
     * matched even by someone holding this file.
     */
    private final String decoyHash;

    AuthenticationService(AuthUserRepository users,
                          PasswordEncoder passwordEncoder,
                          LoginAttemptRecorder attempts,
                          PasswordPolicy passwordPolicy,
                          TotpService twoFactor) {
        this.users = users;
        this.passwordEncoder = passwordEncoder;
        this.attempts = attempts;
        this.passwordPolicy = passwordPolicy;
        this.twoFactor = twoFactor;
        this.decoyHash = passwordEncoder.encode(randomSecret());
    }

    /**
     * Verifies a login identifier and password and resolves the caller's scope.
     *
     * <p>Read-only: A-020 writes nothing. {@code last_login_at} and the
     * {@code failed_attempts} reset belong with A-021's counter, and the
     * {@code LOGIN_SUCCESS} audit row with A-071 — putting a write here now
     * would mean a second, competing update path once those land.
     *
     * <p>{@code identifier} is a username <i>or</i> an email address: S-01
     * (blueprint §7.1) specifies one field accepting either, and resolving it
     * is {@link AuthUserRepository#findByLoginIdentifier}'s job rather than this
     * method's — the choice of column is a data-access concern, and doing it
     * here would put a second copy of the rule in front of every future caller.
     *
     * @throws InvalidCredentialsException on every failure, without saying which
     */
    @Transactional(readOnly = true)
    AuthenticatedUser authenticate(String identifier, String rawPassword, String totpCode) {
        AuthUserRow user = users.findByLoginIdentifier(identifier).orElse(null);

        // Both branches run the full KDF. Do not "optimise" this into an early
        // return when `user` is null — that is the enumeration oracle.
        String hashToVerify = (user != null) ? user.passwordHash() : decoyHash;
        boolean passwordMatches = passwordEncoder.matches(rawPassword, hashToVerify);

        if (user == null || !passwordMatches || !user.active()) {
            if (user != null && !passwordMatches) {
                // A-021. Only a real user with a wrong password counts. A
                // deactivated account is not counted towards a lock it can
                // never benefit from, and an unknown username has no row.
                attempts.recordFailure(user, Instant.now());
            }
            // Logged at DEBUG and without the username: an INFO-level record of
            // every failed attempt writes a list of valid usernames — and
            // eventually a mistyped password — into a file with far wider read
            // access than the users table. A-071's audit log is the deliberate,
            // access-controlled place for this.
            log.debug("Login rejected");
            throw new InvalidCredentialsException();
        }

        // A-021. Reached only with the correct password, which is the entire
        // point of checking the lock HERE and not before the hash comparison.
        // The contract: lockout "is reported as account-locked only *after*
        // correct credentials, for the same reason" — a 423 handed to someone
        // who has not authenticated confirms the account exists, which is the
        // enumeration oracle in different words. Moving this check above the
        // verification would also make a locked account answer faster than an
        // unlocked one, leaking the same fact through timing.
        if (user.isLockedAt(Instant.now())) {
            throw new AccountLockedException(user.lockedUntil());
        }

        // A-029 · blueprint §10.1's `2FA enabled? → TOTP challenge`.
        //
        // Placed HERE — after the password and the lock, before the session is
        // resolved — for the same reason A-021's lockout sits where it does. A
        // "this account needs a code" answer handed to someone who has not
        // proved the password would confirm both that the account exists and
        // that it is protected, which is a list of exactly whom to phish. And
        // because it runs after the KDF, a 2FA-enabled account does not answer
        // faster or slower than one without.
        //
        // Note this runs BEFORE recordSuccess: a correct password with a wrong
        // code must not clear the failure counter, or an attacker holding the
        // password could hold the lockout open indefinitely while grinding the
        // six digits.
        twoFactor.verifyForLogin(user, totpCode);

        attempts.recordSuccess(user);
        return resolveScope(user);
    }

    /**
     * A-024 · re-resolves an already-authenticated caller's identity and scope
     * from the database, for the refresh endpoint.
     *
     * <p><b>No password, and no lock check.</b> Refreshing is not a login: the
     * caller proved who they were up to seven days ago and holds a credential
     * this server issued. Running A-021's lockout here would let any outsider
     * end an active session by typing a wrong password five times against that
     * username — a trivial denial of service against any employee, delivered by
     * the very control meant to protect them. The lock governs the login form,
     * where guessing happens.
     *
     * <p><b>Deactivation, on the other hand, does take effect here</b>, and this
     * is the whole reason the refresh path re-queries instead of trusting the
     * claims already sitting in the stored token. An account disabled on Monday
     * would otherwise keep minting fresh access tokens until its refresh token
     * expired on Sunday. Role changes and project membership changes land the
     * same way — at the next refresh, so at most fifteen minutes stale rather
     * than seven days.
     *
     * @throws InvalidRefreshTokenException if the user is gone or deactivated
     */
    @Transactional(readOnly = true)
    AuthenticatedUser resolveActiveUser(long userId) {
        AuthUserRow user = users.findById(userId).orElse(null);

        if (user == null || !user.active()) {
            // Logged, unlike a failed login, because this is not someone
            // guessing: a refresh token exists, so a real session is being cut
            // short and someone will ask why. The id is safe to record — it is
            // not a credential and this line is reachable only for an account
            // that genuinely held a session.
            log.info("auth: refresh refused for user {} — {}",
                    userId, user == null ? "no such user" : "account deactivated");
            throw new InvalidRefreshTokenException();
        }

        return resolveScope(user);
    }

    /**
     * A-020 · the caller's own identity for {@code GET /me}, re-read rather
     * than reconstructed from the token.
     *
     * <p><b>Re-read on purpose.</b> The access token carries role, permissions
     * and projects, and answering from those claims would be one fewer query —
     * but a token lives fifteen minutes, so a caller moved off a project, or
     * demoted, would keep seeing the old scope described back to them for the
     * rest of that window. The screen this feeds decides which actions to
     * offer; describing a scope the server would refuse is the one thing it
     * must not do. {@code ScheduledReportRunner.callerFor} makes the same
     * argument for the same reason.
     *
     * <p>Empty when the id resolves to nobody or to a deactivated account —
     * the caller holds a still-valid token for an account that has since been
     * switched off, and the route answers 401 rather than describing them.
     */
    Optional<AuthenticatedUser> describe(long userId) {
        return users.findById(userId)
                .filter(AuthUserRow::active)
                .map(this::resolveScope);
    }

    /**
     * Loads the §10.1 claim set. Runs only after the password verified, so a
     * failed attempt costs one indexed lookup and one hash — never these three
     * queries.
     */
    private AuthenticatedUser resolveScope(AuthUserRow user) {
        List<String> permissions = users.findPermissionCodesByRoleId(user.roleId());
        List<Long> projectIds = users.findProjectIdsByUserId(user.id());
        List<Long> reporteeIds = users.findReporteeIdsByManagerId(user.id());
        // A-110. A fourth query on the login path, and only on the login path —
        // the claim rides in the token from here, so ModuleAccessGuard reads a
        // signed string rather than hitting this table per request.
        //
        // The cost of that is the cost of every claim: a grant revoked mid-session
        // stays honoured until the access token expires, 15 minutes at most.
        // Accepted for the same reason `role` and `projects` accept it, and worth
        // stating rather than discovering — if a module ever needs revocation to
        // bite immediately, the answer is the A-025 blacklist by jti, not a
        // per-request read of user_module_access.
        List<String> modules = users.findModuleCodesByUserId(user.id());
        // A-112 · the role inside each of those modules, for
        // OnboardingScopeResolver. Same table, same live-grants predicate and
        // the same 15-minute staleness the paragraph above accepts for
        // `modules` — a role changed mid-session takes effect on the next
        // access token, not on the next request.
        Map<String, String> moduleRoles = users.findModuleRolesByUserId(user.id());

        return new AuthenticatedUser(
                user.id(),
                user.username(),
                user.email(),
                user.fullName(),
                user.roleCode(),
                user.timezone(),
                // A-028 · §10.3's optional 90-day expiry rides on A-026's flag
                // rather than inventing a second forced-change pathway. The
                // effect is identical from here on: the session body reports it,
                // AccessTokenIssuer stamps the claim, PasswordChangeGate refuses
                // everything but /me/password, and PATCH /me/password clears it.
                //
                // No write happens — expiry is derived from a column already in
                // this row, so a stale password costs nothing on the login path
                // and nothing has to be reset when the flag is switched off
                // again. Returns false unmodified while expiry is disabled,
                // which is the default.
                user.mustChangePassword() || passwordPolicy.isExpired(user.passwordChangedAt()),
                permissions,
                projectIds,
                reporteeIds,
                modules,
                moduleRoles);
    }

    private static String randomSecret() {
        byte[] bytes = new byte[32];
        new SecureRandom().nextBytes(bytes);
        return Base64.getEncoder().encodeToString(bytes);
    }
}
