package com.edunext.edutrack.domain.journal;

import com.edunext.edutrack.common.canonical.CanonicalJson;
import com.edunext.edutrack.domain.tickets.TicketEffortLog;
import com.edunext.edutrack.domain.tickets.TicketHistory;
import com.edunext.edutrack.domain.workflow.TicketStageTransition;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.Instant;
import java.time.LocalDate;
import java.util.HexFormat;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * A-042 · the payload contract, pinned.
 *
 * <p>A-041's golden files pin the <i>serialiser</i> — that a sorted key order and
 * a six-digit timestamp come out of {@code CanonicalJson}. They deliberately do
 * not pin which columns a row contributes, and say so. These pin that: the exact
 * bytes {@link ChainPayloads} produces for a row of each protected table.
 *
 * <p>The distinction matters because the two can break independently. A change
 * to {@code CanonicalJson} turns A-041's files red; adding a column to
 * {@code ticket_history} and putting it in the payload leaves them entirely
 * green while invalidating every hash in the database. This is the file that
 * goes red for the second case.
 *
 * <h2>Two locks, following A-041</h2>
 *
 * <p>Each case asserts the bytes against a checked-in file <b>and</b> their
 * SHA-256 against a hex literal in this source, for the reason A-041 gives at
 * length: the natural way to make a golden-file test pass is to regenerate the
 * golden file, and that is natural precisely to someone who has not realised the
 * diff invalidates every stored hash. Regenerating leaves the digest red.
 *
 * <p><b>A failure here is not a test to fix.</b> It means the set of hashed
 * columns has moved, and the rows already written under the old set can no
 * longer be verified. The response is a {@link ChainPayloads#VERSION} bump, an
 * id boundary recorded per table, and a note saying so — not a new literal.
 *
 * <h2>Why these are built from entities and the goldens were not</h2>
 *
 * <p>The files were generated from payload maps written out by hand. If they had
 * been generated by calling {@link ChainPayloads}, they would agree with it for
 * ever and prove nothing — a dropped column would drop out of both sides
 * together. Here the entity goes in and the bytes come out, so the two halves
 * are independent: this test is the only place the mapping from a column to a
 * key is actually asserted.
 */
class ChainPayloadsGoldenFileTest {

    @Test
    @DisplayName("a ticket_history row — every caller-supplied column, no id and no created_at")
    void history() {
        TicketHistory entry = new TicketHistory();
        entry.setTicketId(4711L);
        entry.setCycleNo((short) 2);
        entry.setEventType("STATUS_CHANGED");
        entry.setFieldName("status");
        entry.setOldValue("IN_PROGRESS");
        entry.setNewValue("IN_QA");
        entry.setActorId(88L);
        entry.setActorType("USER");
        // An em dash, a quote and a newline: what a remark picks up from a human
        // being, and what an escaping table has to survive.
        entry.setRemarks("Handed off to QA — \"ready\"\nsee note");
        entry.setCorrection(false);

        assertCanonical("ticket-history",
                "97eeb4530f9e6f481536bf7d101af140127ce642d2283d2e5813b9f09d488210",
                ChainPayloads.of(entry));
    }

    @Test
    @DisplayName("a correction row — the A-043 pair, and a SYSTEM actor with no actor_id")
    void historyCorrection() {
        TicketHistory entry = new TicketHistory();
        entry.setTicketId(4711L);
        entry.setCycleNo((short) 2);
        entry.setEventType("EFFORT_CORRECTED");
        entry.setActorType("SYSTEM");
        entry.setActorId(null);
        entry.setRemarks("Logged against the wrong cycle");
        entry.setCorrection(true);
        entry.setCorrectsEntryId(9001L);

        assertCanonical("ticket-history-correction",
                "acae0a66984f609a4e57120a0d857bf8233ccb1e43f9ce48b2ea96e25aac972a",
                ChainPayloads.of(entry));
    }

    @Test
    @DisplayName("a ticket_effort_logs row — hours are set as 8.00 and hash as 8")
    void effortLog() {
        TicketEffortLog entry = new TicketEffortLog();
        entry.setTicketId(4711L);
        entry.setCycleNo((short) 2);
        entry.setStageCode("DEV");
        entry.setIterationNo((short) 1);
        entry.setUserId(88L);
        entry.setWorkDate(LocalDate.of(2026, 8, 14));
        // DECIMAL(5,2). Written from "8.00" here and read back by A-044 as
        // "8.00" whatever it was written from — stripTrailingZeros is what makes
        // those one value rather than two hashes.
        entry.setHours(new BigDecimal("8.00"));
        entry.setCorrection(false);

        assertCanonical("effort-log",
                "505592fb9c2669dc61bc71135face761529f8ed866684fba95a56636a0f9d7e8",
                ChainPayloads.of(entry));
    }

    @Test
    @DisplayName("an open hop — entered_at is hashed, the three seal columns are not")
    void stageTransition() {
        TicketStageTransition hop = openHop();
        hop.setIterationNo((short) 1);
        hop.setSeqNo(7);
        hop.setFromStage("DEV");
        hop.setToStage("QA");
        hop.setFromUserId(88L);
        hop.setToUserId(91L);
        hop.setActionCode("FORWARD");
        hop.setHandoffNote("Build 2.14 on staging");
        // A whole second, which catches a trimming formatter: six zeros, not one.
        hop.setEnteredAt(Instant.parse("2026-08-14T09:30:00Z"));

        assertCanonical("stage-transition",
                "99ad1be3bab0023f24ebc179e642326081a10f59b9dc06ea0ba078f146bfdb7d",
                ChainPayloads.of(hop));
    }

    @Test
    @DisplayName("a backward hop — its mandatory reason is inside the hash")
    void stageTransitionRework() {
        TicketStageTransition hop = openHop();
        hop.setIterationNo((short) 2);
        hop.setSeqNo(8);
        hop.setFromStage("QA");
        hop.setToStage("DEV");
        hop.setFromUserId(91L);
        hop.setToUserId(88L);
        hop.setActionCode("REWORK");
        hop.setReason("Discount code path still 500s on the second attempt");
        hop.setEnteredAt(Instant.parse("2026-08-14T14:05:33.250000Z"));

        assertCanonical("stage-transition-rework",
                "3039f286d772e1b4fd8733e4020bb6d1909bd822eab87d2bb78afe13cf3a5f94",
                ChainPayloads.of(hop));
    }

    // ── the exclusions, asserted rather than described ──────────────────────

    @Test
    @DisplayName("sealing a hop does not change its payload")
    void sealingDoesNotChangeThePayload() {
        TicketStageTransition hop = openHop();
        hop.setSeqNo(7);
        hop.setToStage("QA");
        hop.setActionCode("FORWARD");
        hop.setEnteredAt(Instant.parse("2026-08-14T09:30:00Z"));

        String open = CanonicalJson.serialise(ChainPayloads.of(hop));

        // What TicketJournal#seal does to the row afterwards — the one mutation
        // the A-008 trigger permits.
        hop.setExitedAt(Instant.parse("2026-08-14T17:45:00Z"));
        hop.setDurationMins(240);
        hop.setCurrent(false);

        assertThat(CanonicalJson.serialise(ChainPayloads.of(hop)))
                .as("a sealed hop must hash exactly as it did when appended, or every sealed row "
                        + "in the ribbon fails verification the first night A-044 runs")
                .isEqualTo(open);
    }

    @Test
    @DisplayName("no database-generated column reaches the payload")
    void generatedColumnsAreAbsent() {
        // Hashing any of these guarantees a mismatch on every row — the one
        // failure that looks exactly like the whole table having been tampered
        // with. They are unsettable through the entity, so this asserts the key
        // is absent rather than trying to set one.
        assertThat(ChainPayloads.of(new TicketHistory()))
                .doesNotContainKeys("id", "created_at", "prev_hash", "row_hash");
        assertThat(ChainPayloads.of(new TicketEffortLog()))
                .doesNotContainKeys("id", "logged_at", "prev_hash", "row_hash");
        assertThat(ChainPayloads.of(new TicketStageTransition()))
                .doesNotContainKeys("id", "created_at", "prev_hash", "row_hash",
                        "exited_at", "duration_mins", "is_current", "current_ticket_id");
    }

    @Test
    @DisplayName("every payload carries the version marker")
    void everyPayloadIsVersioned() {
        assertThat(ChainPayloads.of(new TicketHistory())).containsEntry("_v", ChainPayloads.VERSION);
        assertThat(ChainPayloads.of(new TicketEffortLog())).containsEntry("_v", ChainPayloads.VERSION);
        assertThat(ChainPayloads.of(new TicketStageTransition())).containsEntry("_v", ChainPayloads.VERSION);
    }

    @Test
    @DisplayName("a null column is written, not dropped")
    void nullsSurviveIntoThePayload() {
        // Dropping them would make {"a":null,"b":1} and {"b":1} the same hash, so
        // a column vanishing from ChainPayloads would be undetectable. The
        // serialiser writes nulls; this asserts the builder still hands them over.
        assertThat(ChainPayloads.of(new TicketHistory()))
                .containsKeys("field_name", "old_value", "new_value", "remarks",
                        "actor_id", "corrects_entry_id")
                .containsEntry("field_name", null);
    }

    // ------------------------------------------------------------------

    /** An empty open hop, matching what {@code TicketJournal#append} requires. */
    private static TicketStageTransition openHop() {
        TicketStageTransition hop = new TicketStageTransition();
        hop.setTicketId(4711L);
        hop.setCycleNo((short) 2);
        return hop;
    }

    /**
     * The bytes, then the digest of the bytes — see the class javadoc for why
     * both. Compared as {@code byte[]} because the charset is part of what is
     * pinned: a UTF-16 comparison passes on a JVM whose default encoding turns
     * the em dash into a question mark, which is the row A-044 would then fail.
     */
    private static void assertCanonical(String goldenName, String expectedSha256,
                                        Map<String, ?> payload) {
        byte[] actual = CanonicalJson.bytes(payload);
        byte[] golden = readGolden(goldenName);

        assertThat(new String(actual, StandardCharsets.UTF_8))
                .as("payload for %s — if this differs, the hashed column set has moved and every "
                        + "row written under the old set stops verifying", goldenName)
                .isEqualTo(new String(golden, StandardCharsets.UTF_8));
        assertThat(actual)
                .as("byte-for-byte, not merely character-for-character")
                .isEqualTo(golden);
        assertThat(sha256(actual))
                .as("SHA-256 of the payload. Regenerating %s.json does not move this literal — if "
                        + "you are here because the golden file was updated, read the class javadoc",
                        goldenName)
                .isEqualTo(expectedSha256);
    }

    private static byte[] readGolden(String name) {
        String resource = "/journal/" + name + ".json";
        try (InputStream in = ChainPayloadsGoldenFileTest.class.getResourceAsStream(resource)) {
            assertThat(in).as("golden file %s is missing", resource).isNotNull();
            return in.readAllBytes();
        } catch (IOException e) {
            throw new IllegalStateException("could not read " + resource, e);
        }
    }

    private static String sha256(byte[] input) {
        try {
            return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(input));
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-256 is required by every Java platform", e);
        }
    }
}
  